export const MESSAGELIST_REQUEST = 'MESSAGELIST_REQUEST';
export const MESSAGELIST_SUCCESS = 'MESSAGELIST_SUCCESS';
export const MESSAGELIST_FAILURE = 'MESSAGELIST_FAILURE'; 
export const MESSAGELIST_REFRESH = 'MESSAGELIST_REFRESH';